### PR TITLE
added wp_delete_site

### PR DESCRIPTION
**Pull request by Dudo1985**
Since version 5.1.0 deleted_blog is deprecated.

I've added a control, and if wp version is > 5.10 then use wp_delete_site instead of deleted_blog

More info can be found here https://rudrastyh.com/wordpress-multisite/delete-blog-deprecated.html

### CODE REVIEW

**Comment by vovafeldman** [comment]
@Dudo1985 thanks for the catch! Question: why did you write a new method instead of reusing `_after_site_deleted_callback()`?

**Comment by Dudo1985** [comment]
I wasn't sure about this: then, I thought the soon or later support for `deleted_blog` will come to an end, and will be easier then to just remove the method `_after_site_deleted_callback` instead of editing it again

**Comment by asadowski10** [comment]
Hello,

We have several premium plugins using the SDK and today we are stuck on removing sites.

Can you prioritize this ticket so that we stop hacking premium plugins?

thank you,

**Comment by vovafeldman** [comment]
Note: The action `wpmu_new_blog` was also deprecated and we need to update the code to use `wp_insert_site`.

**Pull request merged**
