### PR TITLE
Updated Spanish translations. Fixed some issues.

### PR DESCRIPTION
**Pull request by davidperezgar**
I'm already a WordPress Translation Editor for Spanish Translations. I've seen some issues, and I decided to fixed them. This is the pull request.

Regards!

### CODE REVIEW

**Comment by davidperezgar** [comment]
Why? Did you review it?

**Comment by vovafeldman** [comment]
@davidperezgar it was automatically closed by GitHub, not sure why 🤷‍♂️

We are managing the SDK's translations on Transifex and I'd love to add you to the Spanish team so you can apply those improvements yourself:
https://www.transifex.com/freemius/wordpress-sdk/language/es_ES/

Send me your Transifex username and I'll add you as the team reviewer.

**Comment by davidperezgar** [comment]
I've applied to transifex. Thanks.

**Comment by davidperezgar** [comment]
Please give me Editor permissions for Transifex user, in order to review the translations. Thanks

**Pull request closed without merging**
