### PR TITLE
Update fs-plugin-functions.php

### PR DESCRIPTION
**Pull request by wpalchemist**
If the only plan is a free plan, display a "download" button instead of a "purchase" button.

### CODE REVIEW

**Comment by vovafeldman** [comment]
Did you test it? From the first look, I don't think the download link will work since the add-on is not in the repo. Or do you plan to host it there?

**Comment by wpalchemist** [comment]
Yes, I tested and it is working fine on my site.  The plugin is hosted in the repo, so the download link does work.

**Comment by wpalchemist** [comment]
Perhaps there should be an option somewhere in the Freemius dashboard for whether or not a plugin is in the repo.

**Comment by vovafeldman** [comment]
Got it. We'll extend that to work in both situations. Thanks!

**Comment by vovafeldman** [comment]
Integrated in e83ee0aa56249b95c652923fa77ed36f72297113

**Pull request closed without merging**
